#!/bin/bash

# based on _p!df.sh
# software shrinkwrap for .epub
# package a-new ... and a-pre-... including codesigning
# upload to o-r-g.com
# relies on relative location of mastered/ directory
# local/in local/out local/mastered
# also relies on create-dmg

WORKING_PATH=`pwd`
IN='local/in'
OUT='local/out'
CREATEDMG='create-dmg'
MASTERED='local/mastered'
O_R_G='/usr/www/users/reinfurt/o-r-g.com/out'
O_R_G_HASH[0]=833e9166990fdf78d11c6981b7ca4e85
O_R_G_HASH[1]=833e9166990fdf78d11c6981b7ca4e85
O_R_G_HASH[2]=41bff5943154e9f2fcf6936406484d77
O_R_G_HASH[3]=41bff5943154e9f2fcf6936406484d77
O_R_G_HASH_INDEX=0
PUBLISH=1

while [ "$1" != "" ]; do
    case $1 in
        -i | --in )             shift
                                IN=$1;;
        -o | --out )            shift
                                OUT=$1;;
        -p | --publish )        shift
                                PUBLISH=1;;
        -h | --help )           echo -e "\
Usage: ./_p!kg [OPTION]... [FILE]...
Create signed .dmg for a-new-program-for-graphic-design \
and a-pre-program-for-graphic-design
Publish .dmgs to o-r-g.com\

  -i, --in              override default in/ directory
  -o, --out             override default out/ directory
  -p, --publish         publish to o-r-g.com (flag 0 or 1)
"
        exit;;
    esac
    shift
done

#
#   0.  init
#

echo "** init **"

rm -r $OUT/*
for FILE in $IN/*
do
    FILENAME=$(basename "$FILE")
    BASENAME=${FILENAME%.*}

    # bash shell expansion
    # https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_04.html

    # { }       multiple
    # ~         prefix
    # $         parameter
    # ` `       execute
    # $(( ))    arithmetic
    # $[ ]      expression
    # " "       ! word splitting
    # ' '       literal
    
    cp "$IN/$FILENAME" "$MASTERED/$BASENAME"
    mkdir "$OUT/$BASENAME"
    # mkdir "$OUT/$BASENAME/ios"
    # mkdir "$OUT/$BASENAME/macos"

    #
    #   0.  .dmg
    #

    ./$CREATEDMG/create-dmg --window-pos 10 10 --window-size 600 400 --text-size 12 --icon-size 96 "$OUT/$BASENAME/$BASENAME.dmg" "$MASTERED/$BASENAME"

    #
    #   1.  .epub
    #

    cp "$MASTERED/$BASENAME/$BASENAME.epub" "$OUT/$BASENAME/"

    #
    #   2.  code sign & verify
    #
    #   rejected source=Unnotarized Developer ID

    # codesign -f -s "Developer ID Application: O-R-G inc." -v $SINGLE_OUT
    # codesign -f -s "Developer ID Application: O-R-G inc. (2T5W462SEL)" -v $SINGLE_OUT
    # spctl -a -t open --context context:primary-signature -v $SINGLE_OUT

    #
    #   3. publish
    #

    if [ $PUBLISH == 1 ]; then
        echo "** publishing to o-r-g.com **"

        # upload .dmg (macOS) and .epub with license (iOS)
        # download sniffs which and serves appropriate

        scp "$OUT/$BASENAME/$BASENAME.dmg" "o-r-g:$O_R_G/${O_R_G_HASH[O_R_G_HASH_INDEX]}/"
        scp "$OUT/$BASENAME/$BASENAME.epub" "o-r-g:$O_R_G/${O_R_G_HASH[O_R_G_HASH_INDEX]}/"

        ((O_R_G_HASH_INDEX++))
    fi

done

echo "** done **"
exit

ls "$OUT/"*
